version: '3.4'

services:
  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: src/CustomerService/Customer.Api/Dockerfile
    ports:
      - "8081:80"
      - "8082:443"
    depends_on:
      - customer.db
      - eventstore
      - kafka
    networks:
      - customer
      - shared

  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: src/BookingService/Booking.Api/Dockerfile
    ports:
      - "8083:80"
      - "8084:443"
    depends_on:
      - booking.db
      - eventstore
      - kafka
    networks:
      - booking
      - shared

  customer.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    networks:
      - customer

  booking.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5435:1433"
    networks:
      - booking

  eventstore:
     image: eventstore/eventstore
     ports:
      - "8080:2113"
      - "1113:1113"
     networks:
      - shared

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
    networks:
      - shared

  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    networks:
      - shared


networks:
  shared:
    driver: bridge
  booking:
    driver: bridge
  customer:
    driver: bridge